---
name: 'ci-build'

on:
  - 'push'

jobs:
  build:
    name: 'Build collectd plugin'
    runs-on: 'ubuntu-latest'
    env:
      DEBIAN_FRONTEND: 'noninteractive'
      CGO_CPPFLAGS: '-I/usr/include/collectd/core/daemon -I/usr/include/collectd/core'
      GOFLAGS: '-mod=vendor'

    steps:
      - name: 'Install collectd-dev'
        run: 'sudo apt install -y collectd-dev'

      - name: 'Checkout code'
        uses: 'actions/checkout@master'

      - name: 'Install go'
        uses: 'actions/setup-go@master'
        with:
          go-version: '1.13.4'

      - name: 'Test code'
        run: 'go test -v ./...'

      - name: 'Build plugin'
        run: 'go build -buildmode=c-shared -o prometheus_scraper.so'

      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@master'
        with:
          name: 'build_shared_plugin'
          path: 'prometheus_scraper.so'

  rpm_package:
    name: 'Build an RPM of the collectd-plugin'
    needs: 'build'
    runs-on: 'ubuntu-latest'
    container:
      image: 'remiferrand/fpm'

    steps:
      - name: 'Download artifact from previous job'
        uses: 'actions/download-artifact@master'
        with:
          name: 'build_shared_plugin'
          path: 'build_shared_plugin'

        # Use a dedicated fpm_root_dir
        # try to circumvent the following problem:
        # $ rpm -qlp collectd-prometheus-scraper-v0.1.0_d12b4c31730ab9ef8db8b12c390c8cbd4f549db8-1.x86_64.rpm 
        # /usr/lib/.build-id <<== ??
        # /usr/lib/.build-id/bb <<== ??
        # /usr/lib/.build-id/bb/069d6d1502a1209248199502be527273607ff1 <<== ??
        # /usr/lib64/collectd/prometheus_scraper.so
      - name: 'Prepare FPM directories'
        run: |
          mkdir -p ./fpm_root_dir/usr/lib64/collectd/ ./pkg && \
          mv build_shared_plugin/prometheus_scraper.so ./fpm_root_dir/usr/lib64/collectd/ && \
          chmod 0755 ./fpm_root_dir/usr/lib64/collectd/prometheus_scraper.so

      - name: 'Package artifact into an RPM'
        run: 'cd fpm_root_dir/ && fpm -s dir -t rpm -p ../pkg/ --license "CECILL-C" --no-rpm-autoreqprov -n "collectd-prometheus-scraper" -v "v0.1.0-${GITHUB_SHA}" --url "https://github.com/riton/collectd-prometheus-scraper" --description "collectd plugin that scrapes prometheus compatible metrics endpoints" --maintainer "Remi Ferrand <remi.ferrand@cc.in2p3.fr>" --depends "collectd < 6.0.0" ./usr'

      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@master'
        with:
          name: 'collectd-prometheus-scraper.rpm'
          path: 'pkg'
